Remove duplicate points from convex hull
spacetelescope/tweakwcs pull request #146
Opened 2021-11-02 13:33 UTC by stsci-hack

This simple update removes any duplicate points determined when computing the convex hull of a SphericalPolygon which happens on occasion.  These duplicate entries in the points describing the convex hull can trigger a ValueError Exception in the acos function when computing the area of the SphericalPolygon created from the list of RA, Dec hull positions.  These changes do not alter the logic for computing the convex hull points, rather it merely insures that the set of points for the convex hull is unique. 

The original problem was found when using this code to align 'j8mbztcnq' with 'drizzlepac.align.perform_align()'.

2021-11-03 12:06 UTC, mcara requested changes
There are a couple of things wrong with this PR. Some, in practice, may not be as severe as it sounds. However, I know this algorithm would not work as it should and so I cannot approve this.

The algorithm removes _all_ duplicates and this is a problem for the following reasons:
1. Convex hull is a closed polygon and last point should be equal to the first one. Your code would remove this property.
2. _Only **same** points **adjacent to each other**_ should be removed as duplicates. A convex hull should not be self-intersecting and so this _may_ be of theoretical interest only (but maybe practical too?). For example, take this code:
```python
In [8]: a = np.array([7, 1, 2, 7, 2, 2, 3, 5, 3, 3])
   ...: _,idx = np.unique(a, return_index=True)
   ...: a[np.sort(idx)]
Out[8]: array([7, 1, 2, 3, 5])
```
I would expect your algorithm to return `[7, 1, 2, 7, 2, 3, 5, 3]` (and ideally, if last point is the same as first, to keep that one too).

Another thing: Are the points really identically the same or there can be some floating-point epsilon variations? Shouldn't we consider two different but very close points "the same"?

2021-11-03 12:08 UTC, mcara commented
Also, you can see that most unit tests on polygons fail.

2021-11-03 12:13 UTC, mcara commented
Also, you can see that most unit tests on polygons fail as well as PEP8. For example, `test_wcsgroupcat_guarded_intersection_area` fails because computed polygon's area is `1.4956924587750109e-12` compared to the expected `2.9904967391303217e-12`.

In addition to fixing the algorithm such that unit tests pass, please add a unit test that tests a similar situation to the one that prompted this PR.

2021-11-03 14:12 UTC, stsci-hack commented
The changes work precisely as needed.
  1.  These changes were implemented PRIOR to the lines of code that actually close the polygon. The next two lines of non-comment code (lines 477-478) explicitly close the polygon.  
  2. The duplicates that need to be removed are exact floating-point duplicates (down to the last digit) and actually appear next to each other in the original determination.  Effectively, if the input was [0.5, 0.4, 0.3. 0.2, 0.2, 0.1, 0.01, -0.15, -0.24], then this algorithm would return [0.5, 0.4, 0.3, 0.2, 0.1, 0.01, -0.15, -0.24].  Actual values generated for actual science data is included below.  
```
print(ra)
np.array([84.14074638, 84.11071529, 84.07133877, 84.07007468, 84.07007468,
       84.07280618, 84.07528509, 84.07728273, 84.14208468, 84.1491391 ,
       84.14855259, 84.14587202, 84.14553271, 84.1424908 , 84.14074638])
print(dec)
array([-69.06920859, -69.06966602, -69.06899013, -69.06614166,
       -69.06614166, -69.01895959, -69.01750574, -69.0166404 ,
       -69.0148294 , -69.014958  , -69.02772996, -69.05760089,
       -69.05935402, -69.06848326, -69.06920859])
```
This is the output from Line 462 that results in an Exception when used to generate a SphericalPolygon instance and the .area() method gets called.  Since this algorithm gets called on a per-chip basis, all we care about is removing any duplicates regardless of their position in the array, since that information is irrelevant to the correct determination of the polygon or its area, yet will trigger an Exception when computing the area.

I will see about adding a new unit test to cover this specific case, and see whether I can understand why the current tests are failing.

2021-11-03 15:21 UTC, stsci-hack commented
The original code in 'wcsimage' did not correctly close the polygon.  Instead of adding the first point as a new last point, it replaced the last point with the first point.  The logic has been revised so that all unique points in the bounding polygon are removed, then the first point is appended at the end to close the polygon. (see 40a7296).  
This allows the current pytest tests to pass again.  Two new pytests were added to evaluate the computation of the area, which originally resulted in the Exception, to insure that this case gets caught in the future.

2021-11-03 15:44 UTC, mcara commented
Thanks for adding unit test but you still have not addressed the issue of FLT differences and the issue that only adjacent identical values should be dropped. Identical coordinates separated by some intermediate points hypothetically show a self-intersecting polygon. This should not happen for a convex hull and so the proposed change in this PR should not remove those. Especially if you have intention to move this code into `convex_hull` itself.

2021-11-03 16:07 UTC, mcara commented
I am not convinced at all this PR is necessary or that it actually solves any problem at all. The algorithm for the `convex_hull` should not allow identical points in the convex hull. Let me illustrate this using an expanded list of coordinates from your own unit test:

```python
In [32]: from tweakwcs.wcsimage import convex_hull
    ...: import numpy as np
    ...: x = np.array([0.0,  0.0, 10.0, 10.0, 30.0, 30.0, 30.0, 10.0, 55.0, 55.0, 55.0, 10.0, 0.0]) - 5
    ...: y = np.array([0.0, 10.0, 10.0,  0.0,  0.0,  0.0,  0.0,  0.0, 55.0, 55.0, 55.0,  0.0, 0.0]) - 5
    ...: convex_hull(x, y)
Out[32]: (array([-5., 25., 50., -5., -5.]), array([-5., -5., 50.,  5., -5.]))
```
The above example disproves that there is an issue at all with duplicate values in the `convex_hull`.

2021-11-03 17:46 UTC, stsci-hack commented
The data I provided in the comments above actually came from the convex_hull function demonstrating with real data that this problem not only exists, but how it manifests.  The changes in d47ee98 insure that this function no longer can have this problem regardless of what function calls it.

2021-11-03 17:52 UTC, mcara commented
Could you, please, post here all image coordinates `x` and `y` with 15 significant digits that produce RA and DEC from your example?

2021-11-04 19:19 UTC, mcara commented
@stsci-hack has provided (offline) pickled data which indicated that created convex hull had distinct vertices in image coordinates but identical vertices when converted to world coordinates. We discussed this and the issue is likely due to loss of accuracy in the WCSLIB when performing WCS transformations.

2021-11-04 19:30 UTC, mcara commented on tweakwcs/tests/test_wcsimage.py
> +    y = np.array([0.0, 10.0, 10.0, 0.0, 0.0, 0.0]) - 5
I realized this (set of **input** data) actually does not produce a convex hull with two very close (or identical) vertices.

2021-11-04 20:00 UTC, closed without merging